variables:
  GIT_STRATEGY: clone

cache:
  key: none
  paths: []
  policy: pull

.gcc-deps: &gcc-deps
  tags:
    - docker
    - linux
  before_script:
    - apt-get update -q || true
    - apt-get install -qy --no-install-recommends
        automake
        libtool
    - apt-get install -qy --no-install-recommends
        libbluetooth-dev
    - apt-get install -qy --no-install-recommends
        cython
        libpython-dev
        python
        python-setuptools
        python-wheel
    - apt-get install -qy --no-install-recommends
        cython3
        libpython3-dev
        python3
        python3-setuptools
        python3-wheel

.build: &build
  stage: build
  script:
    - autoreconf -i
    - ./configure $CONFIGURE_OPTIONS
    - make
  artifacts:
    untracked: true

.test: &test
  stage: test
  script:
    - touch aclocal.m4 configure config.status Makefile.in
    - make -t
    - make check

build:gcc:4:
  image: gcc:4
  <<: *gcc-deps
  <<: *build

test:gcc:4:
  image: gcc:4
  dependencies:
    - build:gcc:4
  <<: *gcc-deps
  <<: *test

build:gcc:5:
  image: gcc:5
  <<: *gcc-deps
  <<: *build

test:gcc:5:
  image: gcc:5
  dependencies:
    - build:gcc:5
  <<: *gcc-deps
  <<: *test

build:gcc:6:
  image: gcc:6
  <<: *gcc-deps
  <<: *build

test:gcc:6:
  image: gcc:6
  dependencies:
    - build:gcc:6
  <<: *gcc-deps
  <<: *test

build:gcc:7:
  image: gcc:7
  <<: *gcc-deps
  <<: *build

test:gcc:7:
  image: gcc:7
  dependencies:
    - build:gcc:7
  <<: *gcc-deps
  <<: *test

build:gcc:8:
  image: gcc:8
  <<: *gcc-deps
  <<: *build

test:gcc:8:
  image: gcc:8
  dependencies:
    - build:gcc:8
  <<: *gcc-deps
  <<: *test

build:gcc:9:
  image: gcc:9
  <<: *gcc-deps
  <<: *build

test:gcc:9:
  image: gcc:9
  dependencies:
    - build:gcc:9
  <<: *gcc-deps
  <<: *test
