os:
  - linux
sudo: false

language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - automake
      - build-essential
      - libbluetooth-dev
      - libtool
      - valgrind
  sonarcloud:
    organization: "lely-industries"
    token:
      secure: "j3cctPQqSVDzi/Z8R3EhONxkvURN7bYAget03D4znUSCyCS2ItxV0j/T1YzyGUedQCMrOmTYL55UFuZtGUS6BFuPyxPTqTih2gi/v9gqddp4F+uacqDhKoIP7YZ4hZ/ISo1u12rmM/GanJkqGer4TmU6J+CMMHQyXjrtieseiBHU9yP1hJJ6f0xu756zpwHp4Htf1zAo3F4Xk9dkm18Tv/oH4JxAKuX/KjQbYPm+DD5JzPykffDabhFiWkP5bSGXRNyoOl7/U/W01GvFOX3KMTmjbz5oQ6hnhfZljE8pFQTfUMP3DYOiCQEYUa9pp/De4NA6wFFNXg3xIYDpF9uUsWGuMO8FOeifYm7AiOb3auq40W60QKOy2aUcDaZLdbxSp8Vcu7U0H7pTJ/VN6aGDp+fygFFsFKF55W284x+dhPSvVpuCMbVDd5DRDq6cyuESBRkrCUip2S2ijfYMHPceClIeRv99ucmDPQyScgh77/U2UfYmCvykNAdpvdmtXgY7QJ1SjKDi+udut7w/g30xTmj+gVst8zb82Ze6zclPOJ1akkt0GHPOMfba1xnWPe31jxYmPFF3I6uI9T1VtoZ8m/Wy4AdIQITQS+CJghYQI4Z4k3qiXq4kw/gpwDj+tXAXoTsJesjfGzAirqgY8E6Rk77rTyXQqbArRFpmiB0Kqpc="

script:
  - autoreconf -i
  - ./configure --disable-python
  - build-wrapper-linux-x86-64 --out-dir bw-output make check
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
